# Generated by Django 6.0 on 2025-12-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Scenario title (e.g., 'At the Café')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the scenario')),
                ('context_tags', models.JSONField(default=list, help_text="Context tags (e.g., ['travel', 'food'])")),
                ('language', models.CharField(help_text="Target language code (e.g., 'es', 'fr')", max_length=5)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Optional scenario image URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scenario is available to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'ordering': ['language', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('gist', 'Gist'), ('chunk', 'Chunk'), ('roleplay', 'Roleplay')], help_text='Type of lesson', max_length=20)),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what the user will learn')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order within scenario (lower = first)')),
                ('steps', models.JSONField(default=list, help_text='Array of lesson step objects')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5, help_text='Estimated time to complete in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lesson is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(help_text='Parent scenario', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.scenario')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['scenario', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the attempt started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the attempt was completed', null=True)),
                ('score', models.FloatField(blank=True, help_text='Score as decimal (0.0 - 1.0)', null=True)),
                ('responses', models.JSONField(default=list, help_text='Array of user responses to steps')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Time spent on lesson in seconds', null=True)),
                ('user', models.ForeignKey(help_text='User who made the attempt', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attempts', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(help_text='Lesson attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='lessons_att_user_id_80a51f_idx'), models.Index(fields=['user', '-started_at'], name='lessons_att_user_id_6b834d_idx')],
            },
        ),
    ]
