/**
 * Sample lesson data for MVP testing.
 *
 * This mirrors the backend seed data.
 * In production, this data will come from the API.
 */

import { Lesson } from '../../types';

export const sampleLessonData: Lesson[] = [
  {
    id: 1,
    scenarioId: 1,
    scenarioTitle: 'At the Cafe',
    lessonType: 'gist',
    title: 'Ordering Coffee',
    description: 'Listen to a customer ordering coffee and understand the main points.',
    order: 1,
    estimatedMinutes: 5,
    steps: [
      {
        type: 'audio',
        id: 'intro',
        audioUrl: '/media/audio/cafe-order-es.mp3',
        title: 'Listen to the conversation',
        description: 'A customer is ordering at a cafe in Madrid. Listen carefully and try to understand what they order.',
      },
      {
        type: 'question',
        id: 'q1',
        question: 'What did the customer order to drink?',
        options: [
          'Un café con leche',
          'Un té',
          'Un zumo de naranja',
          'Agua',
        ],
        correctIndex: 0,
        audioUrl: '/media/audio/cafe-order-es.mp3',
        explanation: "The customer said 'Un café con leche, por favor' - a coffee with milk.",
      },
      {
        type: 'reveal',
        id: 'r1',
        correctAnswer: 'Un café con leche (Coffee with milk)',
        transcript: 'Cliente: Hola, buenos días.\nCamarero: Buenos días! ¿Qué desea?\nCliente: Un café con leche, por favor.\nCamarero: Muy bien. ¿Algo más?\nCliente: No, gracias. ¿Cuánto es?\nCamarero: Son dos euros cincuenta.\nCliente: Aquí tiene. Gracias.\nCamarero: ¡Gracias a usted!',
        translation: "Customer: Hello, good morning.\nWaiter: Good morning! What would you like?\nCustomer: A coffee with milk, please.\nWaiter: Very well. Anything else?\nCustomer: No, thank you. How much is it?\nWaiter: That's two euros fifty.\nCustomer: Here you go. Thank you.\nWaiter: Thank you!",
        keyPhrases: [
          { spanish: 'Buenos días', english: 'Good morning' },
          { spanish: '¿Qué desea?', english: 'What would you like?' },
          { spanish: 'por favor', english: 'please' },
          { spanish: '¿Cuánto es?', english: 'How much is it?' },
        ],
      },
      {
        type: 'question',
        id: 'q2',
        question: 'How much did the coffee cost?',
        options: [
          '1.50 euros',
          '2.00 euros',
          '2.50 euros',
          '3.00 euros',
        ],
        correctIndex: 2,
        audioUrl: '/media/audio/cafe-order-es.mp3',
        explanation: "The waiter said 'Son dos euros cincuenta' - that's 2.50 euros.",
      },
      {
        type: 'reveal',
        id: 'r2',
        correctAnswer: '2.50 euros',
        transcript: 'Camarero: Son dos euros cincuenta.',
        translation: "Waiter: That's two euros fifty.",
        tip: "In Spanish, prices are often said as 'dos euros cincuenta' (two euros fifty) rather than 'dos con cincuenta'.",
      },
    ],
  },
  {
    id: 2,
    scenarioId: 1,
    scenarioTitle: 'At the Cafe',
    lessonType: 'gist',
    title: 'Ordering a Snack',
    description: 'Listen to someone ordering food at the cafe.',
    order: 2,
    estimatedMinutes: 5,
    steps: [
      {
        type: 'audio',
        id: 'intro',
        audioUrl: '/media/audio/cafe-snack-es.mp3',
        title: 'Listen to the conversation',
        description: 'A customer is ordering a snack. What do they choose?',
      },
      {
        type: 'question',
        id: 'q1',
        question: 'What snack did the customer order?',
        options: [
          'Un croissant',
          'Una tostada',
          'Un bocadillo',
          'Un pastel',
        ],
        correctIndex: 1,
        audioUrl: '/media/audio/cafe-snack-es.mp3',
        explanation: "The customer ordered 'una tostada con tomate' - toast with tomato.",
      },
      {
        type: 'reveal',
        id: 'r1',
        correctAnswer: 'Una tostada (Toast)',
        transcript: 'Cliente: Perdón, ¿tienen algo para comer?\nCamarero: Sí, tenemos tostadas, croissants, y bocadillos.\nCliente: Una tostada con tomate, por favor.\nCamarero: Perfecto, ahora se la traigo.',
        translation: "Customer: Excuse me, do you have anything to eat?\nWaiter: Yes, we have toast, croissants, and sandwiches.\nCustomer: Toast with tomato, please.\nWaiter: Perfect, I'll bring it right away.",
        keyPhrases: [
          { spanish: 'Perdón', english: 'Excuse me' },
          { spanish: '¿tienen algo para comer?', english: 'do you have anything to eat?' },
          { spanish: 'ahora se la traigo', english: "I'll bring it right away" },
        ],
      },
    ],
  },
  {
    id: 3,
    scenarioId: 2,
    scenarioTitle: 'Au Café',
    lessonType: 'gist',
    title: 'Commander un café',
    description: 'Écoutez un client commander un café et comprenez les points principaux.',
    order: 1,
    estimatedMinutes: 5,
    steps: [
      {
        type: 'audio',
        id: 'intro',
        audioUrl: '/media/audio/cafe-order-fr.mp3',
        title: 'Écoutez la conversation',
        description: 'Un client commande dans un café parisien. Écoutez attentivement.',
      },
      {
        type: 'question',
        id: 'q1',
        question: "Qu'est-ce que le client a commandé?",
        options: [
          'Un café crème',
          'Un thé',
          'Un chocolat chaud',
          "Un jus d'orange",
        ],
        correctIndex: 0,
        audioUrl: '/media/audio/cafe-order-fr.mp3',
        explanation: "Le client a dit 'Un café crème, s'il vous plaît'.",
      },
      {
        type: 'reveal',
        id: 'r1',
        correctAnswer: 'Un café crème',
        transcript: "Client: Bonjour!\nServeur: Bonjour! Qu'est-ce que je vous sers?\nClient: Un café crème, s'il vous plaît.\nServeur: Très bien. Ce sera tout?\nClient: Oui, merci. C'est combien?\nServeur: Trois euros cinquante.\nClient: Voilà. Merci!\nServeur: Merci à vous!",
        translation: "Customer: Hello!\nWaiter: Hello! What can I get you?\nCustomer: A coffee with cream, please.\nWaiter: Very well. Will that be all?\nCustomer: Yes, thank you. How much is it?\nWaiter: Three euros fifty.\nCustomer: Here you go. Thank you!\nWaiter: Thank you!",
        keyPhrases: [
          { french: 'Bonjour', english: 'Hello' },
          { french: "Qu'est-ce que je vous sers?", english: 'What can I get you?' },
          { french: "s'il vous plaît", english: 'please' },
          { french: "C'est combien?", english: 'How much is it?' },
        ],
      },
    ],
  },
  // Chunk lesson - Spanish cafe phrases
  {
    id: 4,
    scenarioId: 1,
    scenarioTitle: 'At the Cafe',
    lessonType: 'chunk',
    title: 'Cafe Phrases Practice',
    description: 'Practice saying key phrases from the cafe conversation.',
    order: 3,
    estimatedMinutes: 8,
    steps: [
      {
        type: 'repeat',
        id: 'chunk1',
        audioUrl: '/media/audio/chunks/buenos-dias.mp3',
        phrase: 'Buenos días',
        translation: 'Good morning',
        phoneticHint: 'BWAY-nos DEE-ahs',
        tip: 'This is a formal greeting used until around noon.',
      },
      {
        type: 'repeat',
        id: 'chunk2',
        audioUrl: '/media/audio/chunks/que-desea.mp3',
        phrase: '¿Qué desea?',
        translation: 'What would you like?',
        phoneticHint: 'kay deh-SAY-ah',
        tip: 'This is the formal way to ask what someone wants. You might also hear "¿Qué le pongo?" (What can I get you?).',
      },
      {
        type: 'repeat',
        id: 'chunk3',
        audioUrl: '/media/audio/chunks/cafe-con-leche.mp3',
        phrase: 'Un café con leche, por favor',
        translation: 'A coffee with milk, please',
        phoneticHint: 'oon kah-FAY kon LAY-chay, por fah-VOR',
        tip: 'In Spain, "café con leche" is typically half espresso, half hot milk.',
      },
      {
        type: 'repeat',
        id: 'chunk4',
        audioUrl: '/media/audio/chunks/cuanto-es.mp3',
        phrase: '¿Cuánto es?',
        translation: 'How much is it?',
        phoneticHint: 'KWAN-toh es',
        tip: 'A useful phrase for asking prices in any shop or restaurant.',
      },
      {
        type: 'repeat',
        id: 'chunk5',
        audioUrl: '/media/audio/chunks/gracias.mp3',
        phrase: 'Gracias',
        translation: 'Thank you',
        phoneticHint: 'GRAH-thyahs (Spain) / GRAH-syahs (Latin America)',
        tip: 'The "c" in "gracias" sounds like "th" in Spain, but like "s" in Latin America.',
      },
    ],
  },
  // Chunk lesson - French cafe phrases
  {
    id: 5,
    scenarioId: 2,
    scenarioTitle: 'Au Café',
    lessonType: 'chunk',
    title: 'Phrases du Café',
    description: 'Pratiquez les phrases clés de la conversation au café.',
    order: 2,
    estimatedMinutes: 8,
    steps: [
      {
        type: 'repeat',
        id: 'chunk1',
        audioUrl: '/media/audio/chunks/bonjour-fr.mp3',
        phrase: 'Bonjour',
        translation: 'Hello / Good day',
        phoneticHint: 'bohn-ZHOOR',
        tip: 'Always greet with "Bonjour" when entering a shop or café in France - it\'s considered polite.',
      },
      {
        type: 'repeat',
        id: 'chunk2',
        audioUrl: '/media/audio/chunks/quest-ce-que.mp3',
        phrase: "Qu'est-ce que je vous sers?",
        translation: 'What can I get you?',
        phoneticHint: 'kess-kuh zhuh voo SAIR',
        tip: 'A common way for servers to ask what you want to order.',
      },
      {
        type: 'repeat',
        id: 'chunk3',
        audioUrl: '/media/audio/chunks/cafe-creme.mp3',
        phrase: "Un café crème, s'il vous plaît",
        translation: 'A coffee with cream, please',
        phoneticHint: 'uhn kah-FAY KREM, seel voo PLAY',
        tip: '"Café crème" is espresso with steamed milk, similar to a latte.',
      },
      {
        type: 'repeat',
        id: 'chunk4',
        audioUrl: '/media/audio/chunks/cest-combien.mp3',
        phrase: "C'est combien?",
        translation: 'How much is it?',
        phoneticHint: 'say kohm-BYAHN',
        tip: 'A casual way to ask the price. More formal: "Ça fait combien?"',
      },
      {
        type: 'repeat',
        id: 'chunk5',
        audioUrl: '/media/audio/chunks/merci-fr.mp3',
        phrase: 'Merci',
        translation: 'Thank you',
        phoneticHint: 'mehr-SEE',
        tip: 'Add "beaucoup" (boh-KOO) for "thank you very much".',
      },
    ],
  },
  // Roleplay lesson - Spanish cafe conversation
  {
    id: 6,
    scenarioId: 1,
    scenarioTitle: 'At the Cafe',
    lessonType: 'roleplay',
    title: 'Cafe Conversation Practice',
    description: 'Practice responding in a real cafe scenario.',
    order: 4,
    estimatedMinutes: 10,
    steps: [
      {
        type: 'roleplay',
        id: 'roleplay1',
        promptAudioUrl: '/media/audio/roleplay/es-cafe-prompt-1.mp3',
        situation: "You've just walked into a cozy cafe in Barcelona. The waiter approaches your table with a friendly smile.",
        prompt: '"¡Buenos días! ¿Qué le puedo servir?"',
        promptTranslation: 'Good morning! What can I serve you?',
        taskInstruction: 'Greet the waiter and order a coffee with milk.',
        suggestedResponses: [
          {
            phrase: '¡Buenos días! Un café con leche, por favor.',
            translation: 'Good morning! A coffee with milk, please.',
          },
          {
            phrase: 'Hola, buenos días. Me pone un café con leche.',
            translation: 'Hello, good morning. Give me a coffee with milk.',
          },
        ],
        tip: 'Remember to greet back before placing your order - it\'s polite!',
      },
      {
        type: 'roleplay',
        id: 'roleplay2',
        promptAudioUrl: '/media/audio/roleplay/es-cafe-prompt-2.mp3',
        situation: 'The waiter has noted your coffee order and asks if you want anything else.',
        prompt: '"Muy bien. ¿Algo más?"',
        promptTranslation: 'Very well. Anything else?',
        taskInstruction: 'Ask what pastries they have available.',
        suggestedResponses: [
          {
            phrase: '¿Qué pasteles tienen?',
            translation: 'What pastries do you have?',
          },
          {
            phrase: '¿Tienen algo dulce para comer?',
            translation: 'Do you have anything sweet to eat?',
          },
        ],
        tip: '"Pasteles" means pastries/cakes. You can also ask for "bollería" (bakery items).',
      },
      {
        type: 'roleplay',
        id: 'roleplay3',
        promptAudioUrl: '/media/audio/roleplay/es-cafe-prompt-3.mp3',
        situation: "You've finished your coffee and pastry. It's time to pay.",
        prompt: '"Son cuatro euros con cincuenta."',
        promptTranslation: "That's four euros and fifty cents.",
        taskInstruction: 'Pay for your order and thank the waiter.',
        suggestedResponses: [
          {
            phrase: 'Aquí tiene. ¡Gracias!',
            translation: 'Here you go. Thank you!',
          },
          {
            phrase: 'Perfecto, aquí tiene. Muchas gracias.',
            translation: 'Perfect, here you go. Thank you very much.',
          },
        ],
        tip: '"Aquí tiene" literally means "here you have" and is commonly used when handing something to someone.',
      },
    ],
  },
  // Roleplay lesson - French cafe conversation
  {
    id: 7,
    scenarioId: 2,
    scenarioTitle: 'Au Café',
    lessonType: 'roleplay',
    title: 'Conversation au Café',
    description: 'Pratiquez la conversation dans un vrai café.',
    order: 3,
    estimatedMinutes: 10,
    steps: [
      {
        type: 'roleplay',
        id: 'roleplay1',
        promptAudioUrl: '/media/audio/roleplay/fr-cafe-prompt-1.mp3',
        situation: "You've entered a charming Parisian café. The server greets you warmly.",
        prompt: '"Bonjour! Qu\'est-ce que je vous sers?"',
        promptTranslation: 'Hello! What can I get you?',
        taskInstruction: 'Greet the server and order a coffee with cream.',
        suggestedResponses: [
          {
            phrase: "Bonjour! Un café crème, s'il vous plaît.",
            translation: 'Hello! A coffee with cream, please.',
          },
          {
            phrase: "Bonjour! Je voudrais un café crème, s'il vous plaît.",
            translation: 'Hello! I would like a coffee with cream, please.',
          },
        ],
        tip: 'Always start with "Bonjour" - it\'s considered rude to skip the greeting in France!',
      },
      {
        type: 'roleplay',
        id: 'roleplay2',
        promptAudioUrl: '/media/audio/roleplay/fr-cafe-prompt-2.mp3',
        situation: 'The server asks if you would like something to eat with your coffee.',
        prompt: '"Très bien. Avec ça?"',
        promptTranslation: 'Very well. With that?',
        taskInstruction: 'Ask if they have croissants.',
        suggestedResponses: [
          {
            phrase: 'Vous avez des croissants?',
            translation: 'Do you have croissants?',
          },
          {
            phrase: 'Est-ce que vous avez des croissants?',
            translation: 'Do you have any croissants?',
          },
        ],
        tip: '"Avec ça?" is a casual way servers ask if you want anything else. More formal: "Et avec ceci?"',
      },
      {
        type: 'roleplay',
        id: 'roleplay3',
        promptAudioUrl: '/media/audio/roleplay/fr-cafe-prompt-3.mp3',
        situation: "You've enjoyed your coffee and croissant. Time to ask for the bill.",
        prompt: '"Ça vous a plu?"',
        promptTranslation: 'Did you enjoy it?',
        taskInstruction: 'Say you enjoyed it and ask for the bill.',
        suggestedResponses: [
          {
            phrase: "Oui, c'était délicieux! L'addition, s'il vous plaît.",
            translation: "Yes, it was delicious! The bill, please.",
          },
          {
            phrase: "Oui, merci! Je peux avoir l'addition?",
            translation: 'Yes, thank you! Can I have the bill?',
          },
        ],
        tip: '"L\'addition" is the bill. In casual settings, you might hear "la note" instead.',
      },
    ],
  },
];
