# Generated by Django 6.0 on 2025-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(default=list, help_text='Learning goals selected during onboarding'),
        ),
    ]
